import type { LevelDefinition, CheckpointDefinition } from './types';
const checkpoint = (
  id: string,
  x: number,
  y: number,
  width = 90,
): CheckpointDefinition => ({
  id,
  spawn: { x, y },
  area: { x: x - 25, y: y - 8, width, height: 16 },
});
export const atticEscape: LevelDefinition = {
  id: 'attic-escape',
  name: 'Attic Escape',
  width: 3600,
  height: 900,
  fallY: 790,
  playerSpawn: { x: 160, y: 520 },
  atticOpening: { x: 70, y: 520 },
  platforms: [
    { id: 'attic', x: 0, y: 520, width: 420, height: 380, style: 'home' },
    {
      id: 'little-roof',
      x: 465,
      y: 510,
      width: 200,
      height: 390,
      style: 'home',
    },
    {
      id: 'chimney-roof',
      x: 740,
      y: 500,
      width: 210,
      height: 400,
      style: 'brick',
    },
    {
      id: 'dash-runway',
      x: 1040,
      y: 500,
      width: 340,
      height: 400,
      style: 'home',
    },
    {
      id: 'high-jump-runway',
      x: 1540,
      y: 500,
      width: 260,
      height: 400,
      style: 'brick',
    },
    {
      id: 'high-roof',
      x: 1830,
      y: 388,
      width: 370,
      height: 512,
      style: 'home',
    },
    {
      id: 'last-home',
      x: 2470,
      y: 388,
      width: 280,
      height: 512,
      style: 'brick',
    },
    {
      id: 'warehouse',
      x: 3100,
      y: 410,
      width: 500,
      height: 490,
      style: 'warehouse',
    },
  ],
  treats: [
    { id: 'first-treat', x: 1260, y: 468 },
    { id: 'crossing-treat', x: 2930, y: 283 },
  ],
  checkpoints: [
    checkpoint('start', 160, 520),
    checkpoint('basics', 800, 500),
    checkpoint('dash', 1130, 500),
    checkpoint('high', 1640, 500),
    checkpoint('long', 1950, 388, 145),
    checkpoint('combo', 2570, 388, 115),
    checkpoint('factory', 3230, 410),
  ],
  sections: [
    { fromX: 0, title: 'Open air', hint: '← → Move   ·   Z / Space Jump' },
    {
      fromX: 670,
      title: 'Over the rooftops',
      hint: 'Hold jump to go higher. Release for a little hop.',
    },
    {
      fromX: 1040,
      title: 'Across the gap',
      hint: 'X Dash   ·   Aim with the arrow keys',
    },
    {
      fromX: 1540,
      title: 'Higher ground',
      hint: 'Jump, then ↑ + X to reach the high roof.',
    },
    {
      fromX: 1860,
      title: 'Carry your momentum',
      hint: '→ + X, then quickly Z — carry your dash into a long jump.',
    },
    {
      fromX: 2470,
      title: 'One more leap',
      hint: 'Jump, then ↗ + X. Catch the treat, then → + X. Keep steering.',
    },
    {
      fromX: 3100,
      title: 'What’s behind that door?',
      hint: 'The factory is quiet. A little too quiet.',
    },
  ],
  exit: { x: 3454, y: 338, width: 48, height: 72 },
};
