import type { LevelDefinition, CheckpointDefinition } from './types';
import type { BirdDefinition } from '../birds/BirdMotion';
import { crown } from '../balloons/config';
const checkpoint = (
  id: string,
  x: number,
  y: number,
): CheckpointDefinition => ({
  id,
  spawn: { x, y },
  area: { x: x - 38, y: y - 8, width: 76, height: 16 },
});
const bird = (
  id: string,
  left: number,
  right: number,
  baseY: number,
  speed: number,
  offset = 0,
  direction: -1 | 1 = 1,
): BirdDefinition => ({
  id,
  left,
  right,
  baseY,
  speed,
  offset,
  direction,
  phase: 0,
  amplitude: 7,
  frequency: 0.28,
});
export const balloons: LevelDefinition = {
  id: 'balloons',
  name: 'The Balloons',
  theme: 'balloons',
  music: 'assets/audio/drifting-balloons.mp3',
  width: 7100,
  height: 1100,
  fallY: 1000,
  playerSpawn: { x: 185, y: 550 },
  companionSpawn: { x: 140, y: 550 },
  platforms: [
    crown('first-balloon', 60, 550, 280),
    crown('coral-balloon', 575, 550, 220),
    crown('blue-hop', 890, 530, 160),
    crown('rose-hop', 1160, 550, 200),
    crown('amber-hop', 1530, 520, 220),
    crown('moving-launch', 1850, 530, 290),
    crown('high-launch', 2735, 440, 240),
    crown('high-chain-balloon', 3240, 380, 200),
    crown('bird-watch', 3730, 275, 260),
    crown('bird-hop', 4100, 290, 210),
    crown('bird-chain', 4540, 260, 260),
    crown('bird-pair', 5110, 225, 240),
    crown('pizza-launch', 5520, 310, 280),
    {
      id: 'pizza-roof',
      x: 6240,
      y: 450,
      width: 760,
      height: 650,
      style: 'brick',
    },
  ],
  movingPlatforms: [
    {
      id: 'rising-balloon',
      start: { x: 2375, y: 550 },
      end: { x: 2375, y: 430 },
      width: 200,
      height: 8,
      speed: 36,
      easing: 'sine',
      collision: 'top-only',
    },
  ],
  treats: [
    { id: 'first-refill', x: 440, y: 485 },
    { id: 'moving-refill', x: 2255, y: 455 },
    { id: 'moving-exit-refill', x: 2660, y: 375 },
    { id: 'high-refill', x: 3075, y: 330 },
    { id: 'high-chain-one', x: 3510, y: 285 },
    { id: 'high-chain-two', x: 3595, y: 220 },
    { id: 'bird-refill', x: 4410, y: 215 },
    { id: 'bird-chain-one', x: 4900, y: 195 },
    { id: 'bird-chain-two', x: 5005, y: 195 },
    { id: 'pizza-one', x: 5910, y: 255 },
    { id: 'pizza-two', x: 6015, y: 255 },
  ],
  checkpoints: [
    checkpoint('balloon-start', 185, 550),
    checkpoint('balloon-hops', 665, 550),
    checkpoint('moving-balloon', 1970, 530),
    checkpoint('high-sky', 2830, 440),
    checkpoint('high-chain', 3320, 380),
    checkpoint('sparrow-watch', 3830, 275),
    checkpoint('sparrow-chain', 4190, 290),
    checkpoint('sparrow-pair', 4660, 260),
    checkpoint('pizza-crossing', 5650, 310),
  ],
  sections: [
    {
      fromX: 0,
      title: 'One balloon…',
      hint: 'The flat crowns are safe. Follow the bones through the sky.',
    },
    {
      fromX: 575,
      title: 'A little balloon hopping',
      hint: 'Soft landings. Keep your eyes on the next crown.',
    },
    {
      fromX: 1850,
      title: 'Up, then down',
      hint: 'Land on the rising crown. Its rounded sides will not catch you.',
    },
    {
      fromX: 2735,
      title: 'High-sky treats',
      hint: 'Let the bones draw your path. Steer between dashes.',
    },
    {
      fromX: 3730,
      title: 'Room for two',
      hint: 'Watch the sparrows cross. Their routes repeat.',
    },
    {
      fromX: 5520,
      title: "Shelly's Pizza",
      hint: 'Two bones. Three dashes. One very good idea.',
    },
    { fromX: 6240, title: 'Something smells good', hint: 'A little closer…' },
  ],
  exit: { x: 6810, y: 350, width: 80, height: 100 },
  balloons: {
    variants: [
      { platformId: 'first-balloon', palette: 0, pattern: 'stripes' },
      { platformId: 'coral-balloon', palette: 1, pattern: 'diamonds' },
      { platformId: 'blue-hop', palette: 2, pattern: 'stripes' },
      { platformId: 'rose-hop', palette: 3, pattern: 'diamonds' },
      { platformId: 'amber-hop', palette: 4, pattern: 'stars' },
      { platformId: 'moving-launch', palette: 5, pattern: 'stars' },
      { platformId: 'rising-balloon', palette: 2, pattern: 'diamonds' },
      { platformId: 'high-launch', palette: 4, pattern: 'stripes' },
      { platformId: 'high-chain-balloon', palette: 1, pattern: 'diamonds' },
      { platformId: 'bird-watch', palette: 0, pattern: 'stripes' },
      { platformId: 'bird-hop', palette: 3, pattern: 'diamonds' },
      { platformId: 'bird-chain', palette: 5, pattern: 'stars' },
      { platformId: 'bird-pair', palette: 2, pattern: 'stripes' },
      { platformId: 'pizza-launch', palette: 4, pattern: 'stars' },
    ],
    challenges: [
      { checkpoint: 'balloon-start', treats: ['first-refill'] },
      { checkpoint: 'balloon-hops', treats: [] },
      {
        checkpoint: 'moving-balloon',
        treats: ['moving-refill', 'moving-exit-refill'],
      },
      { checkpoint: 'high-sky', treats: ['high-refill'] },
      {
        checkpoint: 'high-chain',
        treats: ['high-chain-one', 'high-chain-two'],
      },
      { checkpoint: 'sparrow-watch', treats: [] },
      { checkpoint: 'sparrow-chain', treats: ['bird-refill'] },
      {
        checkpoint: 'sparrow-pair',
        treats: ['bird-chain-one', 'bird-chain-two'],
      },
      { checkpoint: 'pizza-crossing', treats: ['pizza-one', 'pizza-two'] },
    ],
    birds: [
      bird('hop-sparrow', 1460, 1690, 455, 43, 170),
      bird('watch-sparrow', 3760, 3930, 210, 46, 70),
      bird('crossing-sparrow', 4080, 4290, 215, 48, 180),
      bird('ribbon-sparrow', 4430, 4630, 195, 45, 20),
      bird('pair-high', 4890, 5130, 140, 48, 210),
      bird('pair-low', 5140, 5390, 170, 44, 10),
      bird('pizza-high', 5900, 6120, 190, 45, 200),
      bird('pizza-low', 6020, 6250, 350, 45, 0),
    ],
    destination: {
      roofId: 'pizza-roof',
      landingX: 6280,
      sophie: { x: 6350, y: 450 },
      jimmy: { x: 6295, y: 450 },
      sign: { x: 6260, y: 265, width: 256, height: 171 },
      vent: { x: 6790, y: 354, width: 140, height: 96 },
    },
  },
};
