import type { LevelDefinition, PlatformDefinition } from './types';
import type { RatDefinition } from '../rats/RatMotion';
import type { SteamDefinition } from '../steam/SteamCycle';
import { safeAnchor } from '../maintenance/config';
const floor = (id: string, x: number, width: number): PlatformDefinition => ({
  id,
  x,
  y: 500,
  width,
  height: 400,
  style: 'maintenance',
});
const pipe = (id: string, x: number, height: number): PlatformDefinition => ({
  id,
  x,
  y: 500 - height,
  width: 34,
  height,
  style: 'pipe',
});
const rat = (
  id: string,
  left: number,
  right: number,
  speed: number,
  offset: number,
  direction: -1 | 1 = 1,
): RatDefinition => ({
  id,
  left,
  right,
  floorY: 500,
  speed,
  offset,
  direction,
});
const furnace = (id: string, x: number, width: number): SteamDefinition => ({
  id,
  x,
  width,
  floorY: 500,
  height: 150,
  clearMs: 3200,
  warningMs: 700,
  hissMs: 200,
  activeMs: 950,
  dissipateMs: 550,
});
export const maintenance: LevelDefinition = {
  id: 'maintenance-tunnels',
  name: 'Maintenance Tunnels',
  theme: 'maintenance',
  music: 'assets/audio/maintenance-tunnel.mp3',
  width: 9800,
  height: 900,
  fallY: 820,
  playerSpawn: { x: 185, y: 500 },
  companionSpawn: { x: 140, y: 500 },
  platforms: [
    floor('entry-floor', 0, 2100),
    floor('combination-floor', 2300, 1600),
    floor('fast-floor', 4185, 1665),
    floor('landing-floor', 6220, 1730),
    floor('last-rat-floor', 8120, 450),
    floor('exit-floor', 8770, 1030),
    pipe('entry-pipe-one', 650, 26),
    pipe('entry-pipe-two', 860, 34),
    pipe('first-rat-pipe', 1380, 28),
    pipe('combination-pipe-one', 2670, 30),
    pipe('combination-pipe-two', 3170, 38),
    pipe('fast-pipe-one', 4550, 32),
    pipe('fast-pipe-two', 5070, 38),
    pipe('fast-pipe-three', 5500, 26),
    pipe('final-pipe-one', 6930, 34),
    pipe('final-pipe-two', 7470, 28),
  ],
  treats: [
    { id: 'furnace-chain-one', x: 5950, y: 370 },
    { id: 'furnace-chain-two', x: 6025, y: 370 },
  ],
  checkpoints: [
    safeAnchor('tunnel-entry', 185),
    safeAnchor('rat-introduction', 1160),
    safeAnchor('first-furnace', 1930),
    safeAnchor('pipe-rat-combination', 2430),
    safeAnchor('long-furnace', 3710),
    safeAnchor('fast-rats', 4330),
    safeAnchor('major-furnace', 5650),
    safeAnchor('maintenance-run', 6680),
    safeAnchor('short-furnace', 7760),
    safeAnchor('last-furnace', 8470),
  ],
  sections: [
    {
      fromX: 0,
      title: 'Maintenance Tunnels',
      hint: 'Somewhere above the pizza ovens. Mind the pipes.',
    },
    {
      fromX: 1100,
      title: 'A little company',
      hint: 'Fast feet, familiar paths. Hop over the pipes and watch the rat turn.',
    },
    {
      fromX: 1770,
      title: 'Pressure rising',
      hint: 'A glowing gauge, a little hiss—then steam. Cross while the gap is clear.',
    },
    {
      fromX: 2300,
      title: 'Find the rhythm',
      hint: 'Pipe, rat, safe floor. There is room to catch your breath.',
    },
    {
      fromX: 3540,
      title: 'Across the furnace',
      hint: 'Dash → jump for distance. Hold jump and steer toward the far floor.',
      tutorial: {
        title: 'Long jump',
        steps: [
          'Hold → and press X to dash.',
          'Quickly press and hold Z / Space to jump.',
        ],
      },
    },
    {
      fromX: 4185,
      title: 'Quick little feet',
      hint: 'Separate patrols. Choose your landing, then prepare for the next pipe.',
    },
    {
      fromX: 5560,
      title: 'Follow the bones',
      hint: 'Jump, dash up-right, then follow the treats with → dashes. Watch the far-side rat.',
    },
    {
      fromX: 6620,
      title: 'The maintenance run',
      hint: 'You know the rhythm now. Pipes, rats, and a little steam.',
    },
    {
      fromX: 8470,
      title: 'One last furnace',
      hint: 'Jump, dash, and steer onto the service floor.',
    },
    { fromX: 8790, title: 'Service hatch', hint: 'This way, Jimmy.' },
  ],
  exit: { x: 9440, y: 420, width: 260, height: 80 },
  maintenance: {
    rats: [
      rat('first-rat', 1510, 1670, 140, 130),
      rat('combination-rat-one', 2800, 2950, 148, 115),
      rat('combination-rat-two', 3310, 3490, 155, 40, -1),
      rat('fast-rat-one', 4680, 4840, 165, 100),
      rat('fast-rat-two', 5200, 5390, 170, 150),
      rat('landing-rat', 6280, 6480, 145, 170),
      rat('final-run-rat', 7060, 7230, 165, 120),
      rat('last-rat', 8190, 8320, 150, 90),
    ],
    steam: [
      furnace('first-steam', 2100, 200),
      furnace('long-steam', 3900, 285),
      furnace('chain-steam', 5850, 370),
      furnace('short-steam', 7950, 170),
      furnace('last-steam', 8570, 200),
    ],
    challenges: [
      { checkpoint: 'tunnel-entry', treats: [] },
      { checkpoint: 'rat-introduction', treats: [] },
      { checkpoint: 'first-furnace', treats: [] },
      { checkpoint: 'pipe-rat-combination', treats: [] },
      { checkpoint: 'long-furnace', treats: [] },
      { checkpoint: 'fast-rats', treats: [] },
      {
        checkpoint: 'major-furnace',
        treats: ['furnace-chain-one', 'furnace-chain-two'],
      },
      { checkpoint: 'maintenance-run', treats: [] },
      { checkpoint: 'short-furnace', treats: [] },
      { checkpoint: 'last-furnace', treats: [] },
    ],
    majorView: { fromX: 5510, toX: 6620, left: 5470, width: 1120 },
    destination: {
      triggerX: 9440,
      sophie: { x: 9470, y: 500 },
      jimmy: { x: 9415, y: 500 },
      hatch: { x: 9580, y: 404, width: 128, height: 96 },
    },
  },
};
