import type {
  CheckpointDefinition,
  LevelDefinition,
  PlatformDefinition,
} from './types';
import type { BirdDefinition } from '../birds/BirdMotion';
const scaffold = (
  id: string,
  x: number,
  y: number,
  width: number,
  style: PlatformDefinition['style'] = 'catwalk',
  height = 18,
): PlatformDefinition => ({ id, x, y, width, height, style });
const checkpoint = (
  id: string,
  x: number,
  y: number,
): CheckpointDefinition => ({
  id,
  spawn: { x, y },
  area: { x: x - 44, y: y - 8, width: 88, height: 16 },
});
const bird = (
  id: string,
  left: number,
  right: number,
  baseY: number,
  speed: number,
  direction: -1 | 1,
  phase: number,
  offset = 0,
): BirdDefinition => ({
  id,
  left,
  right,
  baseY,
  speed,
  direction,
  phase,
  offset,
  amplitude: 8,
  frequency: 0.32,
});
export const skyscraper: LevelDefinition = {
  id: 'skyscraper',
  name: 'The Skyscraper',
  music: 'assets/audio/city-lights-above.mp3',
  theme: 'skyscraper',
  width: 2840,
  height: 4500,
  fallY: 4470,
  playerSpawn: { x: 170, y: 4300 },
  companionSpawn: { x: 150, y: 4300 },
  platforms: [
    scaffold('arrival-floor', 60, 4300, 420),
    scaffold('low-crate', 350, 4260, 100, 'crate', 40),
    scaffold('high-crate', 470, 4150, 115, 'crate', 150),
    scaffold('first-beam', 670, 4100, 180),
    scaffold('hanging-one', 925, 4050, 170, 'steel', 42),
    scaffold('chain-one-start', 1400, 3940, 250),
    scaffold('chain-one-end', 1790, 3770, 200),
    scaffold('first-lift-approach', 2000, 3750, 170),
    scaffold('westbound-floor', 1950, 3430, 220),
    scaffold('west-chain-end', 1540, 3194, 210),
    scaffold('west-narrow-beam', 1090, 3080, 160),
    scaffold('ladder-start', 770, 3020, 250),
    scaffold('ladder-end', 635, 2740, 180),
    scaffold('upper-plank', 435, 2700, 150),
    scaffold('second-lift-approach', 395, 2680, 80),
    scaffold('bird-observation-floor', 395, 2300, 360),
    scaffold('bird-hop-landing', 835, 2280, 190),
    scaffold('bird-dash-landing', 1180, 2190, 150),
    scaffold('last-chain-start', 1660, 2070, 200),
    scaffold('last-chain-end', 2040, 1834, 160),
    scaffold('summit-lift-approach', 2210, 1834, 125),
    // The lift opens onto the roof to its right, continuing into Interlude 2.
    scaffold('summit-floor', 2525, 490, 235),
  ],
  movingPlatforms: [
    {
      id: 'hanging-two',
      start: { x: 1160, y: 3990 },
      end: { x: 1190, y: 3990 },
      width: 160,
      height: 42,
      speed: 16,
      pauseMs: 400,
    },
    {
      id: 'west-cargo-swing',
      start: { x: 1310, y: 3145 },
      end: { x: 1290, y: 3145 },
      width: 155,
      height: 42,
      speed: 14,
      pauseMs: 450,
    },
    {
      id: 'bird-cargo-swing',
      start: { x: 1440, y: 2130 },
      end: { x: 1460, y: 2130 },
      width: 180,
      height: 42,
      speed: 14,
      pauseMs: 400,
    },
  ],
  treats: [
    { id: 'cargo-arrow', x: 1320, y: 3890 },
    { id: 'first-chain-bone', x: 1680, y: 3830 },
    { id: 'west-chain-one', x: 1920, y: 3320 },
    { id: 'west-chain-two', x: 1855, y: 3255 },
    { id: 'ladder-one', x: 865, y: 2900 },
    { id: 'ladder-two', x: 865, y: 2830 },
    { id: 'bird-chain-one', x: 1870, y: 1960 },
    { id: 'bird-chain-two', x: 1935, y: 1895 },
  ],
  checkpoints: [
    checkpoint('base', 170, 4300),
    checkpoint('hanging-cargo', 750, 4100),
    checkpoint('first-chain', 1550, 3940),
    checkpoint('first-lift', 2080, 3750),
    checkpoint('west-chain', 2060, 3430),
    checkpoint('west-cargo', 1660, 3194),
    checkpoint('vertical-ladder', 900, 3020),
    checkpoint('west-lift', 710, 2740),
    checkpoint('bird-introduction', 485, 2300),
    checkpoint('bird-hop', 700, 2300),
    checkpoint('bird-dash', 930, 2280),
    checkpoint('bird-cargo', 1275, 2190),
    checkpoint('last-chain', 1730, 2070),
    checkpoint('summit-lift', 2270, 1834),
  ],
  sections: [
    { fromX: 0, title: 'The Skyscraper', hint: 'Follow the scaffold upward.' },
  ],
  exit: { x: 2370, y: 400, width: 90, height: 90 },
  skyscraper: {
    sections: [
      { title: '01 · Above the yard', direction: 1, bottom: 4400 },
      { title: '02 · Across the steel', direction: -1, bottom: 3540 },
      { title: '03 · Open air', direction: 1, bottom: 2410 },
    ],
    arrival: { sophie: { x: 170, y: 4300 }, jimmy: { x: 150, y: 4300 } },
    challenges: [
      {
        checkpoint: 'base',
        section: 0,
        title: 'Up from here',
        hint: 'Climb the crates. Jump, then dash up-right.',
        treats: [],
      },
      {
        checkpoint: 'hanging-cargo',
        section: 0,
        title: 'Hanging cargo',
        hint: 'The cables hold steady. Follow the bone upward.',
        treats: ['cargo-arrow'],
      },
      {
        checkpoint: 'first-chain',
        section: 0,
        title: 'A path through the air',
        hint: 'Jump → dash up-right → bone → dash again.',
        treats: ['first-chain-bone'],
      },
      {
        checkpoint: 'first-lift',
        section: 0,
        title: 'Construction lift ↑',
        hint: 'Step aboard. Jimmy is coming.',
        treats: [],
      },
      {
        checkpoint: 'west-chain',
        section: 1,
        title: 'Turn toward the city',
        hint: 'Jump → dash up-left → bone → dash → bone → dash.',
        treats: ['west-chain-one', 'west-chain-two'],
      },
      {
        checkpoint: 'west-cargo',
        section: 1,
        title: 'A moment to breathe ←',
        hint: 'Rest on the cargo, then keep climbing left.',
        treats: [],
      },
      {
        checkpoint: 'vertical-ladder',
        section: 1,
        title: 'A ladder of bones ↑',
        hint: 'Jump beside the ledge. Dash up, up, then up-left.',
        treats: ['ladder-one', 'ladder-two'],
      },
      {
        checkpoint: 'west-lift',
        section: 1,
        title: 'The next floor',
        hint: 'Across the planks, then onto the lift.',
        treats: [],
      },
      {
        checkpoint: 'bird-introduction',
        section: 2,
        title: 'A little company →',
        hint: 'Watch the bird pass. It keeps the same rhythm.',
        treats: [],
      },
      {
        checkpoint: 'bird-hop',
        section: 2,
        title: 'Wait for an opening',
        hint: 'A small jump. Let the bird go by first.',
        treats: [],
      },
      {
        checkpoint: 'bird-dash',
        section: 2,
        title: 'Time the dash',
        hint: 'Watch, jump, then dash up-right.',
        treats: [],
      },
      {
        checkpoint: 'bird-cargo',
        section: 2,
        title: 'Between the cables',
        hint: 'Find a quiet moment to cross the hanging cargo.',
        treats: [],
      },
      {
        checkpoint: 'last-chain',
        section: 2,
        title: 'One last flight',
        hint: 'Watch the bird’s loop. Follow both bones up-right.',
        treats: ['bird-chain-one', 'bird-chain-two'],
      },
      {
        checkpoint: 'summit-lift',
        section: 2,
        title: 'We made it ↑',
        hint: 'Step onto the lift. Enjoy the view.',
        treats: [],
      },
    ],
    lifts: [
      {
        id: 'east-lift',
        x: 2170,
        width: 190,
        bottomY: 3750,
        topY: 3430,
        rideMs: 3000,
        destination: 'west-chain',
      },
      {
        id: 'west-hoist',
        x: 200,
        width: 195,
        bottomY: 2680,
        topY: 2300,
        rideMs: 3200,
        destination: 'bird-introduction',
      },
      {
        id: 'summit-hoist',
        x: 2335,
        width: 190,
        bottomY: 1834,
        topY: 490,
        rideMs: 8500,
      },
    ],
    birds: [
      bird('watch-bird', 430, 735, 2245, 46, 1, 0),
      bird('hop-bird', 755, 990, 2225, 52, -1, 1.1, 80),
      bird('dash-bird', 1040, 1230, 2170, 56, 1, 2.3, 20),
      bird('cargo-bird', 1360, 1570, 2085, 48, -1, 0.7, 100),
      bird('chain-bird', 1885, 2020, 1910, 50, 1, 2, 60),
    ],
  },
};
